# Generated by Django 4.2.3 on 2023-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='oauth_provider',
            field=models.CharField(choices=[('1', 'NONE'), ('2', 'KAKAO'), ('3', 'GOOGLE')], default=('1', 'NONE'), max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='passwd',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
