# Generated by Django 4.2.3 on 2023-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='refresh_token',
            field=models.CharField(default=None, max_length=350),
        ),
    ]
