# Generated by Django 4.2.3 on 2023-08-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_member_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='refresh_token',
            field=models.CharField(blank=True, default=None, max_length=350),
        ),
    ]
