# Generated by Django 4.2.3 on 2023-08-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_member_refresh_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="updated_at",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
