# Generated by Django 4.2.3 on 2023-09-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_member_created_at_member_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_authorized",
            field=models.BooleanField(default=False),
        ),
    ]
