version: '3'
services:
  web:
    container_name: web
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      TZ: "Asia/Seoul"
  redis: 
    container_name: redis
    image: redis:6.2.6-alpine
    ports: 
      - ${REDIS_BINDING_PORT}:${REDIS_PORT}
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes: 
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_DEFAULT_CONFIG_FILE}:/usr/local/etc/redis/redis.conf
    restart: always
volumes:
  app:
  dbdata:
