# Generated by Django 4.2.3 on 2023-09-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursestyle",
            name="accommodation_style",
        ),
        migrations.RemoveField(
            model_name="coursestyle",
            name="activity_style",
        ),
        migrations.RemoveField(
            model_name="coursestyle",
            name="attraction_style",
        ),
        migrations.RemoveField(
            model_name="coursestyle",
            name="schedule_style",
        ),
        migrations.RemoveField(
            model_name="coursestyle",
            name="travel_keyword",
        ),
        migrations.AddField(
            model_name="coursestyle",
            name="choice_data",
            field=models.JSONField(null=True),
        ),
    ]
