# Generated by Django 4.2.3 on 2023-09-09 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_member_created_at_member_updated_at"),
        ("course", "0002_remove_coursestyle_accommodation_style_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="total_people_cnt",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.member",
            ),
        ),
    ]
