# Generated by Django 4.2.3 on 2023-10-15 00:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_rename_user_course_member"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="course",
            table="courses",
        ),
        migrations.AlterModelTable(
            name="coursestyle",
            table="course_styles",
        ),
    ]
