# Generated by Django 4.2.3 on 2023-10-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_alter_course_course_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("traveling_companion", models.CharField(choices=[], max_length=50)),
                ("is_disablity", models.BooleanField()),
                (
                    "schedule",
                    models.CharField(
                        choices=[("1", "Diligently"), ("2", "Leisurely")], max_length=50
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[("1", "Walking"), ("2", "Dynamic"), ("3", "Calm")],
                        max_length=50,
                    ),
                ),
                (
                    "attraction",
                    models.CharField(
                        choices=[("1", "Urban"), ("2", "Nature")], max_length=50
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        choices=[
                            ("1", "한류"),
                            ("2", "K-POP"),
                            ("3", "첫 부산여행"),
                            ("4", "전통문화"),
                            ("5", "인스타그램"),
                            ("6", "바다"),
                        ],
                        max_length=50,
                    ),
                ),
                ("days", models.IntegerField(null=True)),
                ("location", models.CharField(max_length=50)),
                ("detail", models.JSONField()),
            ],
            options={
                "db_table": "course_data",
            },
        ),
    ]
