# Generated by Django 4.2.3 on 2023-10-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_coursedata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedata",
            name="keyword",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="coursedata",
            name="location",
            field=models.CharField(
                choices=[
                    ("1", "Gijang"),
                    ("2", "Dongnae"),
                    ("3", "Haeundae"),
                    ("4", "Seomyeon"),
                    ("5", "Gwangan"),
                    ("6", "Sasang/Gangseo"),
                    ("7", "Yeongdo"),
                ],
                default=("1", "Gijang"),
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="coursedata",
            name="traveling_companion",
            field=models.CharField(max_length=100),
        ),
    ]
