# Generated by Django 4.2.3 on 2023-10-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0008_alter_coursedata_keyword_alter_coursedata_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedata",
            name="activity",
            field=models.CharField(
                choices=[("1", "Walking"), ("2", "Dynamic"), ("3", "Calm")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coursedata",
            name="attraction",
            field=models.CharField(
                choices=[("1", "Urban"), ("2", "Nature")], max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coursedata",
            name="is_disablity",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="coursedata",
            name="schedule",
            field=models.CharField(
                choices=[("1", "Diligently"), ("2", "Leisurely")],
                max_length=50,
                null=True,
            ),
        ),
    ]
